# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'twitch_reger.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 400)
        MainWindow.setMinimumSize(QtCore.QSize(534, 400))
        MainWindow.setMaximumSize(QtCore.QSize(534, 400))
        MainWindow.setWindowOpacity(0.99)
        MainWindow.setStyleSheet("QMainWindow {background: transparent; \n"
"background-color: #1b1b2f;\n"
"}\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(27, 29, 35, 160);\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    border-radius: 2px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame1 = QtWidgets.QFrame(self.frame)
        self.frame1.setStyleSheet("")
        self.frame1.setObjectName("frame1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout_5.setContentsMargins(-1, -1, 5, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalFrame = QtWidgets.QFrame(self.frame1)
        self.verticalFrame.setStyleSheet("background-color: rgb(32, 32, 57);\n"
"border-radius: 10px;\n"
"")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalLayout_5.addWidget(self.verticalFrame)
        self.verticalLayout_4.addWidget(self.frame1)
        self.verticalFrame1 = QtWidgets.QFrame(self.frame)
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_3.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.verticalFrame1)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.proxy_url_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.proxy_url_lineEdit.setMinimumSize(QtCore.QSize(375, 36))
        self.proxy_url_lineEdit.setStyleSheet("/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(33, 33, 58);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(32, 32, 57);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.proxy_url_lineEdit.setObjectName("proxy_url_lineEdit")
        self.horizontalLayout_2.addWidget(self.proxy_url_lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 35))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(33, 33, 58);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_3.addWidget(self.widget, 0, QtCore.Qt.AlignLeft)
        self.widget1 = QtWidgets.QWidget(self.verticalFrame1)
        self.widget1.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget1.setStyleSheet("")
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 35))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(33, 33, 58);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.line = QtWidgets.QFrame(self.widget1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line, 0, QtCore.Qt.AlignLeft)
        self.comboBox = QtWidgets.QComboBox(self.widget1)
        self.comboBox.setMinimumSize(QtCore.QSize(110, 35))
        self.comboBox.setStyleSheet("QComboBox{\n"
"    background-color: rgb(33, 33, 58);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(32, 32, 57);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setMinimumSize(QtCore.QSize(120, 35))
        self.lineEdit.setStyleSheet("/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(33, 33, 58);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(32, 32, 57);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.line_2 = QtWidgets.QFrame(self.widget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout_3.addWidget(self.widget1)
        self.verticalLayout_4.addWidget(self.verticalFrame1)
        self.frame2 = QtWidgets.QFrame(self.frame)
        self.frame2.setLineWidth(0)
        self.frame2.setObjectName("frame2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.threads_input = QtWidgets.QLineEdit(self.frame2)
        self.threads_input.setMinimumSize(QtCore.QSize(120, 35))
        self.threads_input.setStyleSheet("/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(33, 33, 58);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(32, 32, 57);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.threads_input.setText("")
        self.threads_input.setObjectName("threads_input")
        self.horizontalLayout_3.addWidget(self.threads_input)
        self.accounts_input = QtWidgets.QLineEdit(self.frame2)
        self.accounts_input.setMinimumSize(QtCore.QSize(120, 35))
        self.accounts_input.setToolTip("")
        self.accounts_input.setStyleSheet("/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(33, 33, 58);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(32, 32, 57);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.accounts_input.setText("")
        self.accounts_input.setObjectName("accounts_input")
        self.horizontalLayout_3.addWidget(self.accounts_input)
        self.pushButtonStart = QtWidgets.QPushButton(self.frame2)
        self.pushButtonStart.setMinimumSize(QtCore.QSize(120, 35))
        self.pushButtonStart.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(33, 33, 58);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.horizontalLayout_3.addWidget(self.pushButtonStart)
        self.pushButtonStopThreads = QtWidgets.QPushButton(self.frame2)
        self.pushButtonStopThreads.setMinimumSize(QtCore.QSize(120, 35))
        self.pushButtonStopThreads.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(33, 33, 58);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButtonStopThreads.setObjectName("pushButtonStopThreads")
        self.horizontalLayout_3.addWidget(self.pushButtonStopThreads)
        self.verticalLayout_4.addWidget(self.frame2)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TwitchAutoreg"))
        self.label_2.setText(_translate("MainWindow", "Errors:0"))
        self.label_4.setText(_translate("MainWindow", "Threads:0"))
        self.label.setText(_translate("MainWindow", "Accounts:0"))
        self.label_3.setText(_translate("MainWindow", "Proxies:0"))
        self.proxy_url_lineEdit.setPlaceholderText(_translate("MainWindow", "Proxy URL"))
        self.pushButton_2.setText(_translate("MainWindow", "Load proxy"))
        self.pushButton.setText(_translate("MainWindow", "Choose proxy folder"))
        self.comboBox.setItemText(0, _translate("MainWindow", "http"))
        self.comboBox.setItemText(1, _translate("MainWindow", "socks4"))
        self.comboBox.setItemText(2, _translate("MainWindow", "socks5"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "RuCaptcha Key"))
        self.threads_input.setPlaceholderText(_translate("MainWindow", "Threads"))
        self.accounts_input.setPlaceholderText(_translate("MainWindow", "Accounts Amount"))
        self.pushButtonStart.setText(_translate("MainWindow", "Start"))
        self.pushButtonStopThreads.setText(_translate("MainWindow", "Stop"))
